# Este é o conteúdo para o seu arquivo netlify.toml

[build]
  # O comando que o Netlify usará para construir seu site.
  # Verifique seu package.json se este comando é diferente.
  command = "npm run build"

  # A pasta que o comando acima gera com o site final.
  # Para Create React App é 'build'. Para Vite é 'dist'.
  # Verifique qual pasta é criada quando você roda o build localmente.
  publish = "build"

# Esta regra é VITAL para aplicações React (Single Page Applications).
# Ela garante que todas as rotas (ex: /vocabulary/HSK1) funcionem
# corretamente ao recarregar a página.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
